# MacOS LSCOLORS so directories, symlinks are colored well; Assumes a Dark theme
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:~/workspace/workstation_repave/bin:$PATH

# Homebrew ENV VARs

# Install directory is different for Apple vs. Intel processors
case $(arch) in
    arm64) # Apple Silicon
        export HOMEBREW_PREFIX="/opt/homebrew";
    ;;
    i386) # Intel
        export HOMEBREW_PREFIX="/usr/local";
    ;;
esac

export HOMEBREW_CELLAR="${HOMEBREW_PREFIX}/Cellar";
export HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}";
export PATH="${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin${PATH+:$PATH}";
export MANPATH="${HOMEBREW_PREFIX}/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="${HOMEBREW_PREFIX}/share/info:${INFOPATH:-}";

# Brewfile for `brew bundle`
export HOMEBREW_BUNDLE_FILE="${HOME}/workspace/workstation_repave/assets/Brewfile"

# HACK for Postgres
export PATH=$PATH:${HOMEBREW_PREFIX}/opt/postgresql@16/bin

# Fix for keeping SSL upgraded with Homebrew
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

# Starship for prompt, etc.
eval "$(starship init zsh)"

# fzf for history searching and command line fuzzy matching
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey '^[[A' fzf-history-widget

# Chruby for switching between rubies, including ./.ruby-version
source $HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh
source $HOMEBREW_PREFIX/opt/chruby/share/chruby/auto.sh

# Aliases
alias ls="ls ${ls_opts}"
alias ll="ls -l ${ls_opts}"
alias la="ls -a ${ls_opts}"

# Functions

# usage 'run 10 command --option 1'
# - runs any command with options a number of times
function run() {
    number=$1
    shift
    for i in `seq $number`; do
      $@
    done
}
