# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:~/workspace/workstation_repave/bin:$PATH

# Homebrew updates
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

# Brewfile for `brew bundle`
export HOMEBREW_BUNDLE_FILE="${HOME}/workspace/workstation_repave/assets/Brewfile"

# Fix for keeping SSL upgraded with Homebrew
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

# Starship for prompt, etc.
eval "$(starship init zsh)"

# fzf for history searching and command line fuzzy matching
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey '^[[A' fzf-history-widget

# Chruby for switching between rubies, including ./.ruby-version
source $HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh

# Aliases
alias ls="ls ${ls_opts}"
alias ll="ls -l ${ls_opts}"
alias la="ls -a ${ls_opts}"

# Functions

# usage 'run 10 command --option 1'
# - runs any command with options a number of times
function run() {
    number=$1
    shift
    for i in `seq $number`; do
      $@
    done
}
