#!/usr/bin/env ruby
begin
  require 'rubygems'
  require 'rainbow'
rescue LoadError => e
  puts "Rainbow gem not present."
  puts "Run 'gem install rainbow and try again."
  exit
end
using Rainbow

# include all actors
actors_path = File.join(File.dirname(File.absolute_path(__FILE__)), 'actors')
Dir[File.join(actors_path, '*')].each {|file| require file }

def run_actors(actors)
  puts Rainbow('Executing these actors: ').mediumpurple + actors.join(', ')
  actors.each do |actor|
    if actor.respond_to? :do
      exit unless actor.do
    end

    if actor.respond_to? :setup
      exit unless actor.setup
    end
  end
end

system_and_apps = [
  SudoUpFront,
  WorkspaceDir,
  XcodeSierra,
  Homebrew,
  LinkSlateFile,
  # macos defaults
  # terminal defaults
  # chruby
  # dotfiles
]

ruby_development = [
  RubyInstall,
  Bundler
  # rubymine prefs
]

run_actors system_and_apps
run_actors ruby_development
