#!/usr/bin/env ruby
begin
  require 'rubygems'
  require 'rainbow'
rescue LoadError => e
  puts "Rainbow gem not present."
  puts "Run 'gem install rainbow and try again."
  exit
end
using Rainbow

actors_path = File.join(File.dirname(File.absolute_path(__FILE__)), 'actors')
actors_files = Dir["#{actors_path}/*"]
actors_files.each {|file| require file }

actors = [
  SudoUpFront,
  WorkspaceDir,
  XcodeSierra,
  Homebrew,
  LinkSlateFile,
  RubyInstall,
  Bundler
]

puts Rainbow("Executing these actors: ").mediumpurple + actors.join(", ")

actors.each do |actor|
  exit unless actor.do
  if actor.respond_to? :setup
    exit unless actor.setup
  end
end

# rubymine prefs
# Terminal profile
# macOS defaults
# git

# source ./setup-custom-bash-it-plugins.sh

# git setup
# source ./setup-git-config.sh
# source ./setup-git-duet.sh
