#!/usr/bin/env ruby
begin
  require 'rubygems'
  require 'rainbow'
rescue LoadError => e
  puts "Rainbow gem not present."
  puts "Run 'gem install rainbow and try again."
  exit
end

actors_path = File.join(File.dirname(File.absolute_path(__FILE__)), 'actors')
require File.join(actors_path, 'bundler')
require File.join(actors_path, 'copyfiles')
require File.join(actors_path, 'homebrew')
require File.join(actors_path, 'ruby_install')
require File.join(actors_path, 'sudo_up_front')
require File.join(actors_path, 'workspace_dir')
require File.join(actors_path, 'xcode_sierra')

using Rainbow

actors = [
  SudoUpFront,
  WorkspaceDir,
  XcodeSierra,
  Homebrew,
  CopyFilesToHome,
  RubyInstall,
  Bundler
]

puts Rainbow("Executing these actors: ").mediumpurple + actors.join(", ")

actors.each do |actor|
  exit unless actor.do
  if actor.respond_to? :setup
    exit unless actor.setup
  end
end

# rubymine prefs
# Terminal profile
# macOS defaults
# git

# source ./setup-custom-bash-it-plugins.sh

# git setup
# source ./setup-git-config.sh
# source ./setup-git-duet.sh
