cask_args appdir: "/Applications"

tap 'git-duet/tap'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-drivers'
tap 'thoughtbot/formulae'

brew 'ack'
brew 'aria2'
brew 'chruby'
brew 'direnv'
brew 'git'
brew 'git-duet'
brew 'jq'
brew 'libxml2'
brew 'libxslt'
brew 'mas'
brew 'mysql'
brew 'node'
#brew 'nvim'
brew 'postgresql'
brew 'pstree'
brew 'qt'
brew 'rcm'
brew 'ssh-copy-id'
brew 'ruby-install'
brew 'the_silver_searcher'
brew 'the_platinum_searcher'
brew 'tree'
brew 'watch'
brew 'wget'

cask 'atom'
cask 'deckset'
cask 'dropbox'
#cask 'firefox'
cask 'fluid'
cask 'flycut'
cask 'font-fira-code'
cask 'font-source-code-pro'
cask 'font-jetbrains-mono'
cask 'fujitsu-scansnap-manager' # Only at home - pre-MacOS Catalina
cask 'fujitsu-scansnap-home' # Only at home - Catalina+
cask 'github'
cask 'google-chrome'
cask 'google-drive-file-stream'
cask 'java'
cask 'intellij-idea-ce'
#cask 'macs-fan-control' # only needed for Mac Redwood (to turn off Disk Fan)
cask 'nvalt'
cask 'quicksilver'
cask 'rubymine'
cask 'slack'
cask 'slate'
cask 'vmware-fusion' # Only at home
cask 'xquartz'
cask 'xscope'
cask 'zoomus'

# DWF's Mac App Store apps YMMV; mas list can get your ID's for you
mas "Daisy Disk", id: 411643860
mas "LastPass", id: 926036361
mas "Marked 2", id: 890031187
mas "Server", id: 883878097
mas "Slack", id: 803453959
mas "SomaFM", id: 449155338
mas "Soulver", id: 413965349
mas "ToDoist", id: 585829637
