cask_args appdir: "/Applications"

tap 'homebrew/cask-fonts'
tap 'thoughtbot/formulae'

brew 'ack'
brew 'aria2'
brew 'chruby'
brew 'direnv'
brew 'elixir'
brew 'fzf'
brew 'git'
brew 'libxml2'
brew 'libxslt'
brew 'mas'
brew 'node'
brew 'pstree'
brew 'qt'
brew 'rcm'
brew 'ssh-copy-id'
brew 'starship'
brew 'ruby-install'
brew 'tree'
brew 'watch'
brew 'wget'

cask '1password'
cask 'deckset'
cask 'dropbox'
cask 'fluid'
cask 'flycut'
cask 'font-fontawesome'
cask 'font-fira-code-nerd-font' # Nerd fonts needed for Starship
cask 'font-source-code-pro'
cask 'font-jetbrains-mono-nerd-font' # Nerd fonts needed for Starship
cask 'font-xkcd-script'
cask 'github'
cask 'google-chrome'
cask 'google-drive'
cask 'intellij-idea-ce'
cask 'obsidian'
cask 'rubymine'
cask 'signal'
cask 'slack'
cask 'visual-studio-code'
cask 'xquartz'
cask 'xscope'
cask 'zed'
cask 'zoom'

# DWF's Mac App Store apps YMMV; mas list can get your ID's for you
mas "Daisy Disk", id: 411643860
mas "Marked 2", id: 890031187
mas "Slack", id: 803453959
mas "ToDoist", id: 585829637
