# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:~/workspace/workstation_repave/bin:$PATH

# Starship for prompt, etc.
eval "$(starship init zsh)"

# Brewfile for `brew bundle`
export HOMEBREW_BUNDLE_FILE="${HOME}/workspace/workstation_repave/assets/Brewfile"

# Chruby for switching between rubies, including ./.ruby-version
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Aliases
alias ls="ls ${ls_opts}"
alias ll="ls -l ${ls_opts}"
alias la="ls -a ${ls_opts}"

# History search
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward

# Functions

# usage 'run 10 command --option 1'
# - runs any command with options a number of times
function run() {
    number=$1
    shift
    for i in `seq $number`; do
      $@
    done
}

