# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Starship for prompt, etc.
eval "$(starship init zsh)"

# Chruby for switching between rubies, including ./.ruby-version
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Aliases
alias ls="ls ${ls_opts}"
alias ll="ls -l ${ls_opts}"
alias la="ls -a ${ls_opts}"

# History search
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search

# Functions

# usage 'run 10 command --option 1'
# - runs any command with options a number of times
function run() {
    number=$1
    shift
    for i in `seq $number`; do
      $@
    done
}

# Smarter be for ruby projects
function be() {
  if [ -f "bin/$1" ]; then
    "bin/$@"
  else
    "bundle exec $@"
  fi
}
